### ISSUE TITLE
Don't use `new vscode.Uri.file`

### ISSUE THREAD

**Issue by jrieken** [inu1255/vscode-easy-greenjs#1]
The `vscode.Uri.file`-function is a static member of the `Uri`-class. Calling it with `new` was only possible because vscode used to compile its TypeScript sources to ES5, not ES6. Now calling a static class function using the `new`-keyword isn't possible anymore and results in an error (https://github.com/Microsoft/vscode/issues/69533). 

Please update and use `vscode.Uri.file` without the `new` keyword. 

Thanks and HappyCoding!

**Comment by inu1255** [comment]
it's fixed, Thanks for reminding.
